const chars = [
    { jp: "日", en: "sun" },
    { jp: "一", en: "one" },
    { jp: "大", en: "big" },
    { jp: "年", en: "year" },
    { jp: "中", en: "middle" },
    { jp: "会", en: "to meet" },
    { jp: "人", en: "human being, people" },
    { jp: "本", en: "book" },
    { jp: "月", en: "moon, month" },
    { jp: "長", en: "long" },
    { jp: "国", en: "country" },
    { jp: "出", en: "to go out" },
    { jp: "上", en: "up, top" },
    { jp: "十", en: "10" },
    { jp: "生", en: "life" },
    { jp: "子", en: "child" },
    { jp: "分", en: "minute" },
    { jp: "東", en: "east" },
    { jp: "三", en: "three" },
    { jp: "行", en: "to go" },
    { jp: "同", en: "same" },
    { jp: "今", en: "now" },
    { jp: "高", en: "high, expensive" },
    { jp: "金", en: "money, gold" },
    { jp: "時", en: "time" },
    { jp: "手", en: "hand" },
    { jp: "見", en: "to see, to look" },
    { jp: "市", en: "city" },
    { jp: "力", en: "power" },
    { jp: "米", en: "rice" },
    { jp: "自", en: "oneself" },
    { jp: "前", en: "before" },
    { jp: "円", en: "yen (Japanese currency)" },
    { jp: "合", en: "to combine" },
    { jp: "立", en: "to stand" },
    { jp: "内", en: "inside" },
    { jp: "二", en: "two" },
    { jp: "事", en: "affair, matter" },
    { jp: "社", en: "company, society" },
    { jp: "者", en: "person" },
    { jp: "地", en: "ground, place" },
    { jp: "京", en: "capital" },
    { jp: "間", en: "interval, between" },
    { jp: "田", en: "rice field" },
    { jp: "体", en: "body" },
    { jp: "学", en: "to study" },
    { jp: "下", en: "down, under" },
    { jp: "目", en: "eye" },
    { jp: "五", en: "five" },
    { jp: "後", en: "after" },
    { jp: "新", en: "new" },
    { jp: "明", en: "bright, clear" },
    { jp: "方", en: "direction" },
    { jp: "部", en: "section" },
    { jp: "女", en: "woman" },
    { jp: "八", en: "eight" },
    { jp: "心", en: "heart" },
    { jp: "四", en: "four" },
    { jp: "民", en: "people, nation" },
    { jp: "対", en: "opposite" },
    { jp: "主", en: "main, master" },
    { jp: "正", en: "right, correct" },
    { jp: "代", en: "to substitute, generation" },
    { jp: "言", en: "to say" },
    { jp: "九", en: "nine" },
    { jp: "小", en: "small" },
    { jp: "思", en: "to think" },
    { jp: "七", en: "seven" },
    { jp: "山", en: "mountain" },
    { jp: "実", en: "real" },
    { jp: "入", en: "to enter" },
    { jp: "回", en: "to turn around, time" },
    { jp: "場", en: "place" },
    { jp: "野", en: "field" },
    { jp: "開", en: "to open" },
    { jp: "万", en: "10,000" },
    { jp: "全", en: "whole" },
    { jp: "定", en: "to fix" },
    { jp: "家", en: "house" },
    { jp: "北", en: "north" },
    { jp: "六", en: "six" },
    { jp: "問", en: "question" },
    { jp: "話", en: "to speak" },
    { jp: "文", en: "letter, writings" },
    { jp: "動", en: "to move" },
    { jp: "度", en: "degree, time" },
    { jp: "県", en: "prefecture" },
    { jp: "水", en: "water" },
    { jp: "安", en: "inexpensive, peaceful" },
    { jp: "氏", en: "courtesy name (Mr., Mrs.)" },
    { jp: "和", en: "harmonious, peace" },
    { jp: "政", en: "government, politics" },
    { jp: "保", en: "to maintain, to keep" },
    { jp: "表", en: "to express, surface" },
    { jp: "道", en: "way" },
    { jp: "相", en: "phase, mutual" },
    { jp: "意", en: "mind, meaning" },
    { jp: "発", en: "to start, to emit" },
    { jp: "不", en: "not, un-, in-" },
    { jp: "党", en: "political party" }
];
